# Generated by Django 5.0 on 2023-12-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('alt', models.FloatField()),
                ('speed', models.FloatField()),
                ('orientation', models.FloatField()),
                ('acc', models.IntegerField()),
                ('dil', models.IntegerField()),
                ('towing', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Posicion',
                'verbose_name_plural': 'Posciones',
                'db_table': 'posicion',
            },
        ),
    ]
